run:
  timeout: 2m
  skip-dirs:
    - go
    - opt

linters:
  enable:
    - revive

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA(4003|1019|5011):"

  include:
    - EXC0012
    - EXC0014
