version: '3.0'

services:
  backend_builder:
    image: golang:1.19
    working_dir: /go/src/victorialogs-datasource
    volumes:
      - ./:/go/src/victorialogs-datasource
      - ./.cache:/go/pkg/mod
      - ./.cache:/go-cache
    environment:
      CGO_ENABLED: "0"
    command: |
      bash -xec "
        GOOS=linux GOARCH=amd64 go build -o ./victorialogs-datasource/victorialogs_datasource_plugin_linux_amd64 ./pkg/ && \
        GOOS=linux GOARCH=arm64 go build -o ./victorialogs-datasource/victorialogs_datasource_plugin_linux_arm64 ./pkg/ && \
        GOOS=linux GOARCH=arm go build -o ./victorialogs-datasource/victorialogs_datasource_plugin_linux_arm ./pkg/ && \
        GOOS=linux GOARCH=386 go build -o ./victorialogs-datasource/victorialogs_datasource_plugin_linux_386 ./pkg/ && \
        GOOS=darwin GOARCH=arm64 go build -o ./victorialogs-datasource/victorialogs_datasource_plugin_darwin_arm64 ./pkg/ && \
        GOOS=darwin GOARCH=amd64 go build -o ./victorialogs-datasource/victorialogs_datasource_plugin_darwin_amd64 ./pkg/ && \
        chmod +x ./victorialogs-datasource/victorialogs_datasource_plugin*
      "

  frontend_builder:
    image: node:18.13.0
    working_dir: /victorialogs-datasource
    volumes:
      - ./:/victorialogs-datasource
      # for speedup yarn install
      - "node_modules:/grafana-logs-datasource/node_modules"
    command: |
      bash -xec "
        if [[ "3" == `ls -la ./node_modules/ | wc -l` ]]; then yarn install --omit=dev; fi && \
        yarn run build
      "

  grafana:
    container_name: 'grafana-logs-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.1.2}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./victorialogs-datasource:/var/lib/grafana/plugins/grafana-datasource,
      - ./provisioning:/etc/grafana/provisioning

volumes:
  node_modules:
